# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TsPlayground' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'CodePush', :path => '../node_modules/react-native-code-push'
  
  # Pods for TsPlayground
  pod 'AppCenter/Crashes', '~> 1.1.0'
  pod 'AppCenter/Analytics', '~> 1.1.0'
  pod 'AppCenterReactNativeShared', '~> 1.1.0'

  

  target 'TsPlaygroundTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TsPlayground-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TsPlayground-tvOS

  target 'TsPlayground-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
